### PR TITLE
Adding proper id's to the h3 tags in the markdown files

### PR DESCRIPTION
**Pull request by moekify**
There was no functionality behind the links on the TOS which is not that good for our clients to easily switch to their TOS.

### CODE REVIEW

**Comment by moekify** [comment]
> > Can you make the ids all in english?
> 
> do you know which pages link to this, so we know the ids are correct? it seems some links were localized and some were not

The links are same page anchors, as in they are not pointing anywhere outside the current page anyways. Or what were you referring to and I misunderstood?

**Comment by kdamball** [comment]
@Ryman is that question for Mirko? If for me, I have no idea. Either way, all id's/classes or links should be in english.

**Comment by moekify** [comment]
@kdamball Could you redeploy once the checks have run so I can quickly QA? :)

**Comment by Ryman** [comment]
> @Ryman is that question for Mirko? If for me, I have no idea. Either way, all id's/classes or links should be in english.

well it would be to Marc :P But yeah, I tried grepping with mirko for links to the employer part, but couldnt find any but i thought it was linked from the footer and stuff? (I think in english is correct but I think we need to check and update any links pointing to the localized form, also gotta educate people to not localize links... well actually... if our markdown processor was actually anchorifying the `# footitle` sections then the localized form would be correct here)

**Comment by kdamball** [comment]
@moekify it auto-deploys. Just visit the previous link I sent you

**Comment by moekify** [comment]
@kdamball I QAed all the links on EN/DE/NL. They jump finely now. For the future it might be nice to add a scroll effect so it doesn't feel that jumpy. But absolutely a side thing.

Imho, can be merged in :)

**Pull request merged**
