### PR TITLE
[CU-nn7y91] Remove N26 logo from landing page

### PR DESCRIPTION
**Pull request by heliosam**
ClickUp ticket: #nn7y91

Removes the N26 logo because the customer complained about not being a client anymore.

### CODE REVIEW

**Comment by moekify** [comment]
Task linked: [CU-nn7y91 Removing one Company name and logo from the HP website](https://app.clickup.com/t/nn7y91)

**Comment by heliosam** [comment]
reina: r website#CU-nn7y91/remove-N26-logo

**Comment by heliosam** [comment]
reina: d website#CU-nn7y91/remove-N26-logo

**Comment by heliosam** [comment]
Ok... apparently no reina in this Repo 🙄 😝

**Review by simnau — APPROVED** [review]

**Comment by Agathebadia** [comment]
> Ok... apparently no reina in this Repo 🙄 😝

Static pages deployments are automatically done and work via sub pages with the pr number. E.g. Staging.honeypot.co/pr-xy/en/about

I'll add it in the documentation

**Comment by Agathebadia** [comment]
Ah it's available already on the readme of the repo: https://github.com/honeypotio/website#how-to-qa

**Comment by heliosam** [comment]
I'm getting a 404 though @Agathebadia , any ideas why? https://staging.honeypot.co/pr-160/en/tech-hiring

**Review by Agathebadia — APPROVED** [review]
LGTM 🚀

**Comment by Agathebadia** [comment]
> https://staging.honeypot.co/pr-160/en/tech-hiring

Strange... I checked an older PR, it has this staging URL: http://staging.honeypot.co/pr-145/en/about/ - Even after removing https to http, it doesn't work. I'm not sure what else could be wrong 🤔

**Comment by Agathebadia** [comment]
Checked locally, and the N26 logo is not here anymore ✅ 
All good!

**Pull request merged**
